# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-26 17:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=50)),
                ('datafrom', models.DateField(default=datetime.date.today)),
                ('dataend', models.DateField(default=datetime.date.today)),
                ('plan', models.TextField(max_length=500)),
                ('planedby', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='login_app.User')),
            ],
        ),
    ]
