# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-26 18:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='dataend',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='datafrom',
        ),
    ]
